services:
  api:
    build: ./api
    env_file:
      - ./api/.env
    ports:
      - 3000:3000
    networks:
      - devops_backend

networks:
  devops_backend:
    external: true
  devops_frontend:
    external: true