services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  postgres_data:
    driver: local
