services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - backend

  redis:
    image: redis:7
    ports:
      - 6379:6379
    networks:
      - backend

  npm:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 81:81
    volumes:
      - ./npm:/data
      - ./npm/letsencrypt:/etc/letsencrypt

networks:
  backend:
  frontend:

volumes:
  postgres_data:
    driver: local
